import { useEffect, useState } from 'react';
import { Mail, Pencil, Phone, Plus, Search, UserCheck, UserMinus } from 'lucide-react';
import { toast } from 'sonner';
import { Avatar, AvatarFallback, AvatarImage } from '../components/ui/avatar';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../components/ui/dialog';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { getAdminDirectory, saveAdminDirectory, subscribeToAdminDirectory, type AdminDirectoryEntry } from '../data/adminDirectory';

const palette = ['#c8d3e3','#c4ddcf','#d8cbe9','#c0dbea','#ead8bd','#e6c6cc','#c9d0df','#d7e3c8','#e4d1bd','#c8dfe0'];
const blank = (): AdminDirectoryEntry => ({ id:'', name:'', firstName:'', lastName:'', patronymic:'', shortName:'', initials:'', role:'Администратор', accent:'bg-slate-700', columnTone:'bg-slate-100/90', email:'', phone:'', login:'', active:true, columnColor:palette[0], createdAt:new Date().toISOString() });

export default function Administrators() {
  const [admins,setAdmins]=useState(getAdminDirectory);
  const [query,setQuery]=useState('');
  const [show,setShow]=useState<'active'|'dismissed'>('active');
  const [draft,setDraft]=useState<AdminDirectoryEntry>(blank);
  const [open,setOpen]=useState(false);
  useEffect(()=>subscribeToAdminDirectory(()=>setAdmins(getAdminDirectory())),[]);
  const persist=(next:AdminDirectoryEntry[])=>{setAdmins(next);saveAdminDirectory(next);};
  const filtered=admins.filter(a=>a.active===(show==='active')&&`${a.name} ${a.email} ${a.login} ${a.role}`.toLowerCase().includes(query.toLowerCase()));
  const upload=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')||file.size>2*1024*1024)return toast.error('Фото: JPG, PNG или WebP до 2 МБ');const reader=new FileReader();reader.onload=()=>setDraft(d=>({...d,avatar:String(reader.result)}));reader.readAsDataURL(file);};
  const save=()=>{const firstName=draft.firstName.trim(),lastName=draft.lastName.trim(),patronymic=draft.patronymic?.trim()||'';if(!firstName||!lastName||!draft.login.trim())return toast.error('Заполните имя, фамилию и логин');if(draft.email&&!/^\S+@\S+\.\S+$/.test(draft.email))return toast.error('Проверьте e-mail');if(admins.some(a=>a.id!==draft.id&&a.login.toLowerCase()===draft.login.toLowerCase()))return toast.error('Этот логин уже занят');const name=[firstName,lastName,patronymic].filter(Boolean).join(' ');const entry={...draft,id:draft.id||`admin-${Date.now()}`,firstName,lastName,patronymic,name,shortName:firstName,initials:`${firstName[0]}${lastName[0]}`.toUpperCase()};persist(draft.id?admins.map(a=>a.id===draft.id?entry:a):[...admins,entry]);setOpen(false);toast.success(draft.id?'Профиль обновлён':'Администратор добавлен — колонка в задачах создана');};
  return <div className="space-y-6"><header className="flex items-end justify-between border-b pb-5"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-muted-foreground">Пользователи системы</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Администраторы</h1></div><Button onClick={()=>{setDraft(blank());setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Добавить администратора</Button></header>
  <div className="flex items-center justify-between gap-3"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Имя, должность, логин или e-mail"/></div><div className="flex border p-1"><button onClick={()=>setShow('active')} className={`px-4 py-1.5 text-sm ${show==='active'?'bg-foreground text-background':''}`}>Работают</button><button onClick={()=>setShow('dismissed')} className={`px-4 py-1.5 text-sm ${show==='dismissed'?'bg-foreground text-background':''}`}>Уволены</button></div></div>
  <div className="overflow-hidden border"><div className="hidden grid-cols-[minmax(230px,1.3fr)_1fr_1fr_110px] gap-4 border-b bg-muted/40 px-5 py-3 text-xs uppercase tracking-wider text-muted-foreground md:grid"><span>Администратор</span><span>Доступ</span><span>Контакты</span><span className="text-right">Действия</span></div>{filtered.map(a=><div key={a.id} className="grid gap-4 border-b px-5 py-4 last:border-0 md:grid-cols-[minmax(230px,1.3fr)_1fr_1fr_110px] md:items-center"><div className="flex items-center gap-3"><Avatar><AvatarImage src={a.avatar}/><AvatarFallback style={{backgroundColor:a.columnColor}}>{a.initials}</AvatarFallback></Avatar><div><div className="font-medium">{a.name}</div><div className="text-xs text-muted-foreground">{a.role}</div></div></div><div><Badge variant="outline" className="rounded-none">{a.login}</Badge><div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><span className="h-3 w-3 rounded-full border" style={{background:a.columnColor}}/>Цвет колонки задач</div></div><div className="space-y-1 text-sm text-muted-foreground">{a.email&&<div className="flex gap-2"><Mail className="h-4 w-4"/>{a.email}</div>}{a.phone&&<div className="flex gap-2"><Phone className="h-4 w-4"/>{a.phone}</div>}</div><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" onClick={()=>{setDraft({...a});setOpen(true)}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>{persist(admins.map(x=>x.id===a.id?{...x,active:!x.active}:x));toast.success(a.active?'Администратор уволен':'Администратор восстановлен')}}>{a.active?<UserMinus className="h-4 w-4 text-red-600"/>:<UserCheck className="h-4 w-4 text-emerald-600"/>}</Button></div></div>)}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{draft.id?'Редактирование администратора':'Добавление администратора'}</DialogTitle><DialogDescription>После сохранения активному администратору автоматически создаётся колонка в «Задачах».</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="flex items-center gap-4 sm:col-span-2"><Avatar className="h-16 w-16"><AvatarImage src={draft.avatar}/><AvatarFallback style={{background:draft.columnColor}}>{draft.initials||'АД'}</AvatarFallback></Avatar><Label htmlFor="admin-photo" className="cursor-pointer border px-4 py-2 text-sm">{draft.avatar?'Заменить фото':'Добавить фото'}</Label><Input id="admin-photo" className="hidden" type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/>{draft.avatar&&<Button variant="ghost" onClick={()=>setDraft({...draft,avatar:undefined})}>Удалить</Button>}</div><div className="space-y-1.5"><Label>Имя *</Label><Input value={draft.firstName} onChange={e=>setDraft({...draft,firstName:e.target.value})}/></div><div className="space-y-1.5"><Label>Фамилия *</Label><Input value={draft.lastName} onChange={e=>setDraft({...draft,lastName:e.target.value})}/></div><div className="space-y-1.5 sm:col-span-2"><Label>Отчество</Label><Input value={draft.patronymic||''} onChange={e=>setDraft({...draft,patronymic:e.target.value})}/></div><div className="space-y-1.5"><Label>Должность</Label><Input value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}/></div><div className="space-y-1.5"><Label>Логин *</Label><Input value={draft.login} onChange={e=>setDraft({...draft,login:e.target.value})}/></div><div className="space-y-1.5"><Label>E-mail</Label><Input value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></div><div className="space-y-1.5"><Label>Телефон</Label><Input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></div><div className="space-y-2 sm:col-span-2"><Label>Цвет колонки в задачах</Label><div className="flex flex-wrap gap-2">{palette.map(c=><button key={c} aria-label={`Выбрать ${c}`} onClick={()=>setDraft({...draft,columnColor:c})} className={`h-8 w-8 rounded-full border-2 ${draft.columnColor===c?'border-foreground':'border-transparent'}`} style={{background:c}}/>)}</div></div><div className="space-y-1.5 sm:col-span-2"><Label>Роль доступа</Label><Select defaultValue="administrator"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="administrator">Администратор</SelectItem><SelectItem value="senior">Старший администратор</SelectItem><SelectItem value="director">Руководитель</SelectItem></SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Отмена</Button><Button onClick={save}>Сохранить</Button></DialogFooter></DialogContent></Dialog></div>;
}
