-- Deutsch-Klub CRM: group management domain (DRAFT, DO NOT APPLY YET)
-- Convert this file into a timestamped Supabase migration only after auditing
-- the current self-hosted database and testing it on a disposable/local database.

begin;

create extension if not exists pgcrypto;

create type public.crm_student_status as enum ('studying', 'thinking', 'waiting', 'finished', 'declined');
create type public.crm_group_status as enum ('planned', 'active', 'completed', 'archived');
create type public.crm_task_status as enum ('new', 'in_progress', 'waiting', 'completed');
create type public.crm_task_priority as enum ('low', 'medium', 'high', 'urgent');
create type public.crm_membership_payment_status as enum ('not_paid', 'half_paid', 'paid', 'trial');

create table public.crm_groups (
  id uuid primary key default gen_random_uuid(),
  group_number bigint generated always as identity unique,
  name text not null,
  language text not null check (language in ('German', 'English')),
  level text not null,
  course_type text not null,
  teacher_id text,
  teacher_name text not null default '',
  textbook text not null default '',
  academic_hours integer not null default 0 check (academic_hours >= 0),
  price numeric(12, 2) not null default 0 check (price >= 0),
  max_students integer not null default 12 check (max_students > 0),
  start_date date not null,
  end_date date,
  status public.crm_group_status not null default 'planned',
  internal_note text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);

comment on column public.crm_groups.group_number is 'Immutable human-facing group number; generated by PostgreSQL.';

create table public.crm_students (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  middle_name text,
  phone text,
  email text,
  birth_date date,
  profession text,
  source text,
  primary_language text not null default 'German' check (primary_language in ('German', 'English')),
  current_level text not null default 'A1',
  status public.crm_student_status not null default 'waiting',
  loyal_client boolean not null default false,
  student_discount boolean not null default false,
  friend_referral_discount boolean not null default false,
  social_discount boolean not null default false,
  internal_note text not null default '',
  archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.crm_group_memberships (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.crm_groups(id) on delete cascade,
  student_id uuid not null references public.crm_students(id) on delete restrict,
  payment_status public.crm_membership_payment_status not null default 'not_paid',
  is_studying boolean not null default true,
  joined_at date not null default current_date,
  left_at date,
  removal_reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_id, student_id),
  check (left_at is null or left_at >= joined_at)
);

comment on table public.crm_group_memberships is 'Group enrolment is removed independently; the student profile is retained.';

create table public.crm_group_schedule_rules (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.crm_groups(id) on delete cascade,
  weekday smallint not null check (weekday between 1 and 7),
  start_time time not null,
  end_time time not null,
  room_name text,
  zoom_room text,
  valid_from date not null,
  valid_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time > start_time),
  check (valid_until is null or valid_until >= valid_from)
);

create table public.crm_lessons (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.crm_groups(id) on delete cascade,
  schedule_rule_id uuid references public.crm_group_schedule_rules(id) on delete set null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  room_name text,
  zoom_room text,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled', 'moved')),
  previous_lesson_id uuid references public.crm_lessons(id) on delete set null,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.crm_task_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null unique,
  default_description text not null default '',
  default_priority public.crm_task_priority not null default 'medium',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.crm_task_templates (title, sort_order) values
  ('Тык на прод группы', 10),
  ('Набирать группу', 20),
  ('Письмо о продолжении', 30),
  ('Опросник', 40)
on conflict (title) do nothing;

create table public.crm_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  group_id uuid references public.crm_groups(id) on delete set null,
  student_id uuid references public.crm_students(id) on delete set null,
  template_id uuid references public.crm_task_templates(id) on delete set null,
  assignee_id uuid references auth.users(id) on delete set null,
  due_at timestamptz,
  priority public.crm_task_priority not null default 'medium',
  status public.crm_task_status not null default 'new',
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.crm_comments (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references public.crm_groups(id) on delete cascade,
  student_id uuid references public.crm_students(id) on delete cascade,
  task_id uuid references public.crm_tasks(id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (num_nonnulls(group_id, student_id, task_id) = 1)
);

create table public.crm_student_files (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.crm_students(id) on delete cascade,
  storage_bucket text not null default 'crm-student-files',
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index crm_group_memberships_student_idx on public.crm_group_memberships(student_id) where left_at is null;
create index crm_group_memberships_group_idx on public.crm_group_memberships(group_id) where left_at is null;
create index crm_lessons_group_starts_idx on public.crm_lessons(group_id, starts_at);
create index crm_tasks_assignee_status_idx on public.crm_tasks(assignee_id, status, due_at);
create index crm_tasks_group_idx on public.crm_tasks(group_id) where group_id is not null;
create index crm_tasks_student_idx on public.crm_tasks(student_id) where student_id is not null;
create index crm_students_name_idx on public.crm_students(lower(last_name), lower(first_name));

create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'crm_groups', 'crm_students', 'crm_group_memberships', 'crm_group_schedule_rules',
    'crm_lessons', 'crm_task_templates', 'crm_tasks', 'crm_comments'
  ] loop
    execute format('create trigger %I before update on public.%I for each row execute function public.crm_set_updated_at()', table_name || '_set_updated_at', table_name);
  end loop;
end $$;

-- Authenticated CRM staff must receive crm_role in app_metadata through an
-- administrator-controlled Auth operation. Never derive authorization from user_metadata.
create or replace function public.crm_is_staff()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((select auth.jwt() -> 'app_metadata' ->> 'crm_role'), '')
    in ('administrator', 'senior_administrator', 'director');
$$;

revoke all on function public.crm_is_staff() from public, anon;
grant execute on function public.crm_is_staff() to authenticated, service_role;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'crm_groups', 'crm_students', 'crm_group_memberships', 'crm_group_schedule_rules',
    'crm_lessons', 'crm_task_templates', 'crm_tasks', 'crm_comments', 'crm_student_files'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon', table_name);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    execute format('create policy %I on public.%I for select to authenticated using ((select public.crm_is_staff()))', table_name || '_staff_select', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select public.crm_is_staff()))', table_name || '_staff_insert', table_name);
    execute format('create policy %I on public.%I for update to authenticated using ((select public.crm_is_staff())) with check ((select public.crm_is_staff()))', table_name || '_staff_update', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using ((select public.crm_is_staff()))', table_name || '_staff_delete', table_name);
  end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;

-- The private Storage bucket and storage.objects policies are deliberately
-- excluded until the self-hosted Storage configuration is audited.

rollback;
